import { Bank } from '../types';
import { db } from '../db';

export const DEFAULT_BANK_ICON = '/logos/bank-icon.png';

export const BANKS: Bank[] = [
  {
    id: 'tbank',
    name: 'Т-Банк',
    color: '#FFDD2D',
    logoText: 'Т',
    logoUrl: '/logos/tbank.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'sber',
    name: 'Сбербанк',
    color: '#21A038',
    logoText: 'С',
    logoUrl: '/logos/sber.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'alfa',
    name: 'Альфа-Банк',
    color: '#EF3124',
    logoText: 'А',
    logoUrl: '/logos/alfa.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'vtb',
    name: 'ВТБ',
    color: '#0A2896',
    logoText: 'В',
    logoUrl: '/logos/vtb.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'raif',
    name: 'Райффайзен',
    color: '#FEE600',
    logoText: 'Р',
    logoUrl: '/logos/raiff.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'gazprom',
    name: 'Газпромбанк',
    color: '#00145A',
    logoText: 'Г',
    logoUrl: '/logos/gazprom.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'ozon',
    name: 'Ozon Банк',
    color: '#005BFF',
    logoText: 'O',
    logoUrl: '/logos/ozon.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'yandex',
    name: 'Яндекс Банк',
    color: '#FFCC00',
    logoText: 'Я',
    logoUrl: '/logos/yandex.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'uralsib',
    name: 'Уралсиб',
    color: '#004B87',
    logoText: 'У',
    logoUrl: '/logos/uralsib.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'psb',
    name: 'ПСБ',
    color: '#E35F14',
    logoText: 'П',
    logoUrl: '/logos/psb.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'rshb',
    name: 'РСХБ',
    color: '#006B3D',
    logoText: 'РС',
    logoUrl: '/logos/rshb.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'mkb',
    name: 'МКБ',
    color: '#E3000F',
    logoText: 'М',
    logoUrl: '/logos/mkb.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'sovcom',
    name: 'Совкомбанк',
    color: '#0033A0',
    logoText: 'СВ',
    logoUrl: '/logos/sovcom.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'mts',
    name: 'МТС Банк',
    color: '#E30611',
    logoText: 'МТ',
    logoUrl: '/logos/mts.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'rnkb',
    name: 'РНКБ',
    color: '#0055A5',
    logoText: 'РН',
    logoUrl: '/logos/rnkb.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'domrf',
    name: 'Банк ДОМ.РФ',
    color: '#00A19C',
    logoText: 'Д',
    logoUrl: '/logos/domrf.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'ubrir',
    name: 'УБРиР',
    color: '#E3000F',
    logoText: 'УБ',
    logoUrl: '/logos/ubrir.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'rencredit',
    name: 'Ренессанс',
    color: '#FF4B5F',
    logoText: 'РК',
    logoUrl: '/logos/renaissance.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'otp',
    name: 'ОТП Банк',
    color: '#007A33',
    logoText: 'ОТ',
    logoUrl: '/logos/otp.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'avangard',
    name: 'Авангард',
    color: '#0033A0',
    logoText: 'АВ',
    logoUrl: '/logos/avangard.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
  {
    id: 'bspb',
    name: 'БСПБ',
    color: '#0033A0',
    logoText: 'БС',
    logoUrl: '/logos/bsaintpet.png',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  },
];

export const getAllBanks = async (): Promise<Bank[]> => {
  const customBanks = await db.banks.toArray();
  return [...BANKS, ...customBanks];
};

export const getBankDetails = (
  bankId: string,
  allBanks: Bank[] = BANKS,
): Bank => {
  const bank = allBanks.find((b) => b.id === bankId || b.name === bankId);
  if (bank) return bank;

  return {
    id: 'custom',
    name: bankId || 'Банк',
    color: '#64748b', // slate-500
    logoText: (bankId || 'Б').charAt(0).toUpperCase(),
    logoUrl: '',
    iconScale: 1,
    iconOffsetX: 0,
    iconOffsetY: 0,
  };
};
